---

- name: "zookeeper | {{ ansible_hostname }} | Set ZooKeeper member index"
  when: zookeeper_member_index is not defined
  set_fact:
    zookeeper_member_index: "{{ zookeeper_members|get_member_index(zookeeper_member_id) }}"

- name: "zookeeper | {{ ansible_hostname }} | Create ZooKeeper config dir"
  file:
    path: "{{ zookeeper_conf_dir }}"
    state: directory
    mode: '0755'
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"

- name: "zookeeper | {{ ansible_hostname }} | Create ZooKeeper config file"
  template:
    src: zookeeper.cfg.j2
    dest: "{{ zookeeper_conf_dir }}/zookeeper.cfg"
    mode: '0644'
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
  notify: Restart ZooKeeper

- name: "zookeeper | {{ ansible_hostname }} | Create ZooKeeper dynamic config file"
  template:
    src: zookeeper.dynamic.cfg.j2
    dest: "{{ zookeeper_conf_dir }}/zookeeper.dynamic.cfg"
    mode: '0644'
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"

- name: "zookeeper | {{ ansible_hostname }} | Create JAAS config file"
  template:
    src: jaas.cfg.j2
    dest: "{{ zookeeper_conf_dir }}/jaas.cfg"
    mode: '0600'
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
  notify: Restart ZooKeeper

- name: "zookeeper | {{ ansible_hostname }} | Create myid file"
  copy:
    dest: "{{ zookeeper_data_dir }}/myid"
    content: "{{ zookeeper_member_index }}"
    mode: '0644'
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
  notify: Restart ZooKeeper

- name: "zookeeper | {{ ansible_hostname }} | Create env file"
  template:
    src: zookeeper.env.j2
    dest: "{{ zookeeper_conf_dir }}/zookeeper.env"
    mode: '0644'
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
  notify: Restart ZooKeeper

- name: "zookeeper | {{ ansible_hostname }} | Create JMX password file"
  template:
    src: jmxremote.password.j2
    dest: "{{ zookeeper_conf_dir }}/jmxremote.password"
    mode: '0600'
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
  notify: Restart ZooKeeper

- name: "zookeeper | {{ ansible_hostname }} | Create JMX access file"
  template:
    src: jmxremote.access.j2
    dest: "{{ zookeeper_conf_dir }}/jmxremote.access"
    mode: '0600'
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
  notify: Restart ZooKeeper
