---
- name: "zookeeper | {{ ansible_hostname }} | Add ZooKeeper group"
  group:
    name: zookeeper
    state: present

- name: "zookeeper | {{ ansible_hostname }} | Add ZooKeeper user"
  user:
    name: zookeeper
    group: "{{ zookeeper_group }}"

- name: "zookeeper | {{ ansible_hostname }} | Create ZooKeeper dir"
  file:
    path: "{{ zookeeper_dir }}"
    state: directory
    mode: '0755'
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"

- name: "zookeeper | {{ ansible_hostname }} | Create ZooKeeper version dir"
  file:
    path: "{{ zookeeper_dir }}/{{ zookeeper_version }}"
    state: directory
    mode: '0755'
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
  register: zookeeper_version_dir

- name: "zookeeper | {{ ansible_hostname }} | Download and extract ZooKeeper"
  unarchive:
    src: "{{ zookeeper_download_url }}"
    dest: "{{ zookeeper_dir }}/{{ zookeeper_version }}"
    remote_src: yes
    extra_opts: [--strip-components=1]
  when: zookeeper_version_dir.changed

- name: "zookeeper | {{ ansible_hostname }} | Create ZooKeeper data dir"
  file:
    path: "{{ zookeeper_data_dir }}"
    state: directory
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
    mode: '0755'

- name: "zookeeper | {{ ansible_hostname }} | Create ZooKeeper log dir"
  file:
    path: "{{ zookeeper_log_dir }}"
    state: directory
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
    mode: '0755'

- name: "zookeeper | {{ ansible_hostname }} | Create ZooKeeper service"
  template:
    src: zookeeper.service.j2
    dest: "/etc/systemd/system/zookeeper.service"
    mode: '0644'
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
  register: zookeeper_service
  notify: Update ZooKeeper
