---
- name: Install required roles
  hosts: all
  roles:
    - nl2go.openjdk

- name: Download JMX CLI
  hosts: all
  tasks:
    - name: Download foo.conf
      get_url:
        url: https://github.com/jiaqi/jmxterm/releases/download/v1.0.1/jmxterm-1.0.1-uber.jar
        dest: /opt/jmxterm.jar
        mode: '0755'
