---
- name: Verify ZooKeeper state
  hosts: all
  tasks:
    - name: Get ZooKeeper service status
      command: service zookeeper status
      register: service_status
      changed_when: no
    - name: Verify ZooKeeper is running
      assert:
        that:
          - "'active (running)' in service_status.stdout"
    - name: Get ZooKeeper server status
      shell: echo srvr | nc localhost 2181
      register: server_status
      changed_when: no
    - name: Verify ZooKeeper server are connected
      assert:
        that:
          - "'Connections: 1' in server_status.stdout"
    - name: Verify ZooKeeper server version
      assert:
        that:
          - "'{{ zookeeper_version }}' in server_status.stdout"
    - name: Verify ZooKeeper server mode
      assert:
        that:
          - "'Mode: leader' in server_status.stdout or 'Mode: follower' in server_status.stdout"
    - name: Get open ports
      command: netstat -tulpn | grep java
      register: port_status
      changed_when: no
    - name: Verify JMX ports and host
      assert:
        that:
          - "'{{ zookeeper_jmx_host }}:{{ zookeeper_jmx_rmi_port }}' in port_status.stdout"
          - "'{{ zookeeper_jmx_host }}:{{ zookeeper_jmx_port }}' in port_status.stdout"
    - name: Test JMX connection
      shell: echo "exit" | java -jar /opt/jmxterm.jar -l {{ zookeeper_jmx_host }}:{{ zookeeper_jmx_port }} -u {{ zookeeper_jmx_username }} -p {{ zookeeper_jmx_password }}
      register: jmx_status
      changed_when: no
    - name: Verify JMX connection
      assert:
        that:
          - "'Welcome to JMX terminal' in jmx_status.stderr"
    - name: Get mntr status
      shell: echo mntr | nc localhost 2181
      register: mntr_status
      changed_when: no
    - name: Verify mntr status
      assert:
        that:
          - "'zk_version	{{ zookeeper_version }}' in mntr_status.stdout"
    - name: Get ZooKeeper process log
      shell: cat /var/log/zookeeper/zookeeper-*.out
      register: log_result
      changed_when: no
    - name: Verify ZooKeeper configuration options
      assert:
        that:
          - "'Created server with tickTime {{ zookeeper_tick_time }} minSessionTimeout {{ zookeeper_min_session_timeout }} \
           maxSessionTimeout {{ zookeeper_max_session_timeout }}' in log_result.stdout"
          - "'initLimit set to {{ zookeeper_init_limit }}' in log_result.stdout"
          - "'syncLimit set to {{ zookeeper_sync_limit }}' in log_result.stdout"
    - name: Get ZooKeeper process information
      shell: ps uax | grep zookeeper
      register: process_result
      changed_when: no
    - name: Verify ZooKeeper process settings
      assert:
        that:
          - "'-Xmx{{ zookeeper_heap_size }}m' in process_result.stdout"
