---
- name: Get open ports
  command: netstat -tulpn | grep java
  register: port_status
  changed_when: no
- name: Verify JMX ports and host
  assert:
    that:
      - "'{{ zookeeper_jmx_host }}:{{ zookeeper_jmx_rmi_port }}' in port_status.stdout"
      - "'{{ zookeeper_jmx_host }}:{{ zookeeper_jmx_port }}' in port_status.stdout"
- name: Test JMX connection
  shell: echo "exit" | java -jar /opt/jmxterm.jar -l {{ zookeeper_jmx_host }}:{{ zookeeper_jmx_port }} -u {{ zookeeper_jmx_username }} -p {{ zookeeper_jmx_password }}
  register: jmx_status
  changed_when: no
- name: Verify JMX connection
  assert:
    that:
      - "'Welcome to JMX terminal' in jmx_status.stderr"
